version: "3"

services:
    generator:
        build: ./generator
        environment:
          KAFKA_BROKER_URL: broker:9092
  

# Give this composition access to the Kafka network
networks:
  default:
    external:
      name: kafka-network